### ISSUE TITLE
"make bias" error

### ISSUE THREAD

**Issue by ghost** [francozappa/bias#13]
Hello,

I am currently testing BIAS based on https://github.com/francozappa/bias/tree/master/bias you provided.

There was no problem until the bias.py file creates.

In the next step ("make bias" to patch CYW920819 devboard firmware), i got the following error.

<img width="769" alt="스크린샷 2020-06-18 오후 4 27 40" src="https://user-images.githubusercontent.com/67093841/84991010-e8547200-b180-11ea-8d8f-52728d9eadac.png">

Could you please let me know what is the solution for this issue?

**Comment by francozappa** [comment]
Can you try running the command with `python2`?

**Comment by ghost** [comment]
I have tried to run the command with python2.

> sudo python2 bias.py

I got the following error.

<img width="450" alt="스크린샷 2020-06-19 오전 12 04 55" src="https://user-images.githubusercontent.com/67093841/85039173-6c7b1980-b1c2-11ea-89c0-f9c47db9834a.png">

The import error is solved by installing "pwntools".

I have tried to rerun the command with python2.

However, I could see another error like this:

<img width="411" alt="스크린샷 2020-06-19 오전 12 10 37" src="https://user-images.githubusercontent.com/67093841/85040380-b4e70700-b1c3-11ea-9fb5-587fa9fc1cb4.png">

**Comment by francozappa** [comment]
Have you installed `internalblue`?

**Comment by playground7** [comment]
I have tried to install internalblue.

There was a Python version issue.

<img width="698" alt="스크린샷 2020-06-19 오전 5 46 16" src="https://user-images.githubusercontent.com/67093841/85070460-cb578780-b1f0-11ea-829a-ab60265710ac.png">

The internalblue was installed by running the command with python3.

**Comment by ghost** [comment]
Yes, I have installed internalblue using the command with pip3.

I solved all "TypeError" issues, so I could patch CYW920819 devboard firmware.

**Comment by francozappa** [comment]
OK, great!

**Comment by hnznhr** [comment]
Hello,

I have the same problem,

Can you provide how to solve the problem including "TypeError" issues.
