### ISSUE TITLE
Entering Diagnostic Mode

### ISSUE THREAD

**Issue by ghost** [francozappa/bias#3]
Maybe you know why. Somehow I cannot enter `diagnostic mode`:

More in this issue:

https://github.com/seemoo-lab/internalblue/issues/27#issuecomment-635279148

Thanks,

**Comment by DuCkBlAcK** [comment]
Hi bro, 

I think I have the almost same issue as yours.
In addition, I even cannot 'up' my CYW920819EVB-02....
When I run hciconfig, is shown on the list. But the status is 'DOWN'.
Then I run 'hciconfig hci1 up' (hci1 is my dev board). It shows timeout.
Do you have any idea?

Many thanks

**Comment by francozappa** [comment]
@marcinguy 

I've pushed to the master branch the modification to the `linux-4.14.111` kernel that we developed to parse the H4 diagnostic commands. You can try to build such kernel and test the attack.

**Comment by ghost** [comment]
With the modified kernel it seems to work. Also seems like rom Patching works on CYW27035B1. Will try to perform "bias" on test device.
