### ISSUE TITLE
IF Data for Samsung S3 after parsing pairing exchange

### ISSUE THREAD

**Issue by ghost** [francozappa/bias#5]
Hi,

I did a pairing and captured H4/LMP data for my test mobile.

```
{
    "if": "Samsung s3.json",
    "lmin": "07",
    "lmax": "07",
    "btadd": "aa:bb:cc:dd:ee:ff",
    "btname": "BIASing",
    "lmpver": "6", (
    "companyid": "29",
    "subversion": "2003",
    "lmpfp0": "fffe8ffed83f5b87",
    "lmpfp1": "0f00000000000000",
    "lmpfp2": "4503000000000000",
    "iocaps": "01",
    "authreq": "03",
    "oobdata": "0",
    "deviceclass": "5a020c"
}
```

Found all of them except:

lmin,lmax

lmpfp0
lmpfp1
lmpfp2

Can you advise how to find lmin,lmax and lmpfp0,lmpfp1,lmpfp2??? Best with JSON key names in Wireshark.

Thanks,

**Comment by ghost** [comment]
I think I can get Feature Pages via 

sudo hcitool -i dev info bt addr

Lmin and lmax I can brute force, unless you know where to look for them. Should not be hard.

**Comment by ghost** [comment]
1 <=Lmax, Lmin <= 16. So is this correct that we will have 16 possibilities for each? Do they always be the same lmax=Lmin? Or it was just a coincidence in your devices

**Comment by ghost** [comment]
Sorry for stupid questions. Don't work with BT daily. Making BT security crash course now

**Comment by francozappa** [comment]
the lmp features can be extracted while monitoring the LMP traffic from the Samsung device.

lmin and lmax are the values that you want to use to negotiate the entropy of the session key. They are not specific to a device!

**Comment by ghost** [comment]
@francozappa Thanks found them all. Used lmin and lmax also with 7. 

Still have some issues or knowledge gaps. Opened this issue:

https://github.com/francozappa/bias/issues/6
