### ISSUE TITLE
One question about Kernel patching

### ISSUE THREAD

**Issue by DuCkBlAcK** [francozappa/bias#7]
Hi,

Thank you very much that you shared the Linux Kernel patches.
I'm a very beginner on Linux, an have some questions maybe super stupid:
1. My kernel version is 5.3.0, Ubuntu. So I need to install the 4.14.111 kernel firstly then install your patches?
2. How can I install these patches? directly change the files from here to my /usr/src/xxx-headers?(I think it is incorrect)

Many thanks.

**Comment by DuCkBlAcK** [comment]
Hi

The way I use is: I download a pure 4.14.111 kernel. Then replace the .c and .h files to the same path.
When I make the kernel, there is an error:

![image](https://user-images.githubusercontent.com/32911071/83420488-4c74f780-a459-11ea-88d3-d7f0b3fd0d5c.png)

**Comment by DuCkBlAcK** [comment]
Then I tried to change your function name in hci_core.c, I change the function name from hci_recv_bcm_diag to hci_recv_bcm_diag1. And also change the name when it is called in hci_core.c, it seems like it compile well in that place, but new error happened.


I think my method is wrong to patch, but how can I do that?
I'm sorry this question seems so stupid but I really have no idea.
![image](https://user-images.githubusercontent.com/32911071/83422054-8ba44800-a45b-11ea-87a9-e231a73ea5d5.png)

Many thanks.

**Comment by francozappa** [comment]
Hi,

You should download the vanilla kernel and replace the files that I pushed in the repo into the vanilla kernel tree by removing the vanilla file and replacing it with the file in this repo. Then you have to compile and install the kernel.

There are many guides on how to compile and install a Linux kernel, here is the first one that I found https://www.cyberciti.biz/tips/compiling-linux-kernel-26.html

**Comment by DuCkBlAcK** [comment]
> Hi,
> 
> You should download the vanilla kernel and replace the files that I pushed in the repo into the vanilla kernel tree by removing the vanilla file and replacing it with the file in this repo. Then you have to compile and install the kernel.
> 
> There are many guides on how to compile and install a Linux kernel, here is the first one that I found https://www.cyberciti.biz/tips/compiling-linux-kernel-26.html

Hi,

Many thanks! 
I have down this step.
