### ISSUE TITLE
Error with enable_diag.py

### ISSUE THREAD

**Issue by michesemina** [francozappa/bias#9]
Hello,

I'm trying to execute enable_diag.py on board CYW920819EVB-02 but I had this error

Traceback (most recent call last):
  File "enable_diag.py", line 5, in <module>
    s.send(b"\x07\xf0\x01")
socket.error: [Errno 22] Invalid argument

Any idea of this error?

Thank you

**Comment by DuCkBlAcK** [comment]
Hi

I faced to the same issue, I think you need to rebuild a edited Linux kernel to fix it.
you can see here: 

https://github.com/francozappa/bias/issues/3

Hope it will help you

**Comment by francozappa** [comment]
@DuCkBlAcK thanks for answering!
